import React from 'react';
import { AdBanner } from '../components/AdBanner';

export const AboutPage: React.FC = () => {
    return (
        <div className="max-w-4xl mx-auto bg-slate-800/50 rounded-xl ring-1 ring-slate-700 p-8 space-y-8">
            <div>
                <h1 className="text-3xl font-bold text-white mb-4">About Zedge Image SEO AI Assistant</h1>
                <p className="text-slate-300 leading-relaxed">
                    Welcome to the Image SEO AI Assistant, a powerful tool designed to revolutionize how you optimize your images for search engines. In today's digital landscape, visibility is everything. High-quality, well-optimized images can dramatically improve your website's traffic and user engagement. However, manually crafting compelling titles, descriptions, and tags for dozens or hundreds of images is a tedious and time-consuming task.
                </p>
                <p className="mt-4 text-slate-300 leading-relaxed">
                    This is where our tool comes in. By leveraging the advanced capabilities of Google's Gemini AI, we automate the entire process. Simply upload your images, and our assistant will analyze the content of each picture and generate SEO-friendly metadata that is both relevant and effective.
                </p>
            </div>
            
            <AdBanner type="banner" />

            <div>
                <h2 className="text-2xl font-bold text-white mb-3">Our Mission</h2>
                <p className="text-slate-300 leading-relaxed">
                    Our mission is to empower creators, marketers, and web developers with intelligent tools that save time and deliver results. We believe that everyone should have access to the benefits of AI without needing to be an expert. Our focus is on creating intuitive, powerful, and secure applications that streamline workflows and enhance productivity. We are committed to protecting your privacy, which is why your API key and images are processed securely and never stored on our servers.
                </p>
            </div>

             <div>
                <h2 className="text-2xl font-bold text-white mb-3">Why Choose Us?</h2>
                 <ul className="list-disc list-inside space-y-2 text-slate-300">
                    <li><strong>Efficiency:</strong> Generate SEO for multiple images in a single click, saving hours of manual work.</li>
                    <li><strong>Quality:</strong> Get high-quality, context-aware metadata generated by a state-of-the-art AI model.</li>
                    <li><strong>Security:</strong> Your API key is stored only in your browser's local storage and is never exposed.</li>
                    <li><strong>Customization:</strong> Fine-tune the generation settings to match your specific SEO strategy.</li>
                </ul>
            </div>
        </div>
    );
};